name: License Signing (Beta)
on:
  push:
    branches: [ beta ]
    paths:
      - 'csr-list.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
      - name: Issue License
        #if: github.event_name == 'push'
        id: issue-license
        env:
          EC_PPRS: ${{ secrets.ADM_PPS }}
          EC_PVK: ${{ secrets.ADM_KEY }}
          EC_PBK: ${{ secrets.ADM_CER }}
          EC_TKN: ${{ secrets.ADM_TKN }}
        run: | 
          rm ./deploy.sh ./before_deploy.sh
          wget https://raw.githubusercontent.com/EC-Release/certifactory/disty/deploy.sh
          wget https://raw.githubusercontent.com/EC-Release/certifactory/disty/before_deploy.sh
          chmod 775 ./deploy.sh ./before_deploy.sh
          source ./before_deploy.sh
          source ./deploy.sh
      - name: Send license confirmation email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.ADM_EML_SVR }}
          server_port: 587
          username: ${{secrets.ADM_EML_USR}}
          password: ${{secrets.ADM_EML_PWD}}
          subject: EC-Release > Certifactory > License > Approval
          # Literal body:
          body: |
            ### License Confirmation
            Congratulations! your license (Subscription ID ${{ env.DEV_ID }}) has been approved. Attached please find the license certificate for future reference. A copy of the license is also available to [download here](https://github.com/${{ github.repository }}/tree/disty/cert-list/beta). Please conact ec-research@ge.com if you have any questions.
      
      
            Thank you,
            
            Enterprise-Connect, the product team.
          # Read file contents as body:
          attachments: ./../license.txt
          to: ${{ env.lic_email }}
          from: EC Autobot <ec.autobot@outlook.com>
          # Optional carbon copy recipients
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/main.js 
